Made readme accurate to current build process
HurricanePootis/team-comtress-2 pull request #11
Opened 2020-09-22 17:10 UTC by int-72h

I added pretty much everything I think.

2020-09-22 17:13 UTC, HurricanePootis approved these changes
Pog

2020-09-22 17:16 UTC, melvyn2 requested changes

2020-09-22 17:16 UTC, melvyn2 commented on README.md
> +3) Install your TF2 assets into `../game/tf`, the `game` folder should be outside the repo folder (Note: the `../game/tf` folder will already be there as it's made from the compilation). If you have
Command should be `cp -rn ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/* ./`.

This so also a bit wordy, could this be simplified?

2020-09-22 17:16 UTC, melvyn2 commented on README.md
> +- curl with GNUTLS support (note: if you get an error in compiling due to `-lcurl-gnutls` being missing, you need a symlink: `sudo ln -s /usr/lib32/libcurl-gnutls.so.4 /usr/lib32/libcurl-gnutls.so` *
should be `libcurl-gnutls`. Also, remove the first 'note:'.

2020-09-22 17:16 UTC, melvyn2 commented on README.md
> +4) Run in the `../game` folder `./run.sh`
`run.sh` is in the source root folder, not game.

2020-09-22 17:20 UTC, int-72h commented on README.md
> +- curl with GNUTLS support (note: if you get an error in compiling due to `-lcurl-gnutls` being missing, you need a symlink: `sudo ln -s /usr/lib32/libcurl-gnutls.so.4 /usr/lib32/libcurl-gnutls.so` *
A lot of people got an error that was specifically that. I don't see why I need to remove it.

2020-09-22 17:22 UTC, int-72h commented on README.md
> +3) Install your TF2 assets into `../game/tf`, the `game` folder should be outside the repo folder (Note: the `../game/tf` folder will already be there as it's made from the compilation). If you have
The commands do the same thing.
Will try and simplify wording.

2020-09-22 17:23 UTC, melvyn2 commented on README.md
> +- curl with GNUTLS support (note: if you get an error in compiling due to `-lcurl-gnutls` being missing, you need a symlink: `sudo ln -s /usr/lib32/libcurl-gnutls.so.4 /usr/lib32/libcurl-gnutls.so` *
I misspoke: I meant remove the word 'note:', and keep the rest.

2020-09-22 17:29 UTC, int-72h commented on README.md
> +- curl with GNUTLS support (note: if you get an error in compiling due to `-lcurl-gnutls` being missing, you need a symlink: `sudo ln -s /usr/lib32/libcurl-gnutls.so.4 /usr/lib32/libcurl-gnutls.so` *
Done.

2020-09-22 17:32 UTC, melvyn2 requested changes

2020-09-22 17:32 UTC, melvyn2 commented on README.md
> +0) Make sure the path leading up the `team-comtress-2` has no spaces in it. This will lead to errors compiling protobud and gperf.
Typo (protobud)

2020-09-22 17:32 UTC, melvyn2 commented on README.md
> +3) Install your TF2 assets into `../game/tf`. If you have TF2 and steam installed on the same drive, running `cp -rn '~/.steam/steam/steamapps/common/Team Fortress 2/*' ./` will work.
Still wrong command.

2020-09-22 17:32 UTC, melvyn2 commented on README.md
> +3) Install your TF2 assets into `../game/tf`, the `game` folder should be outside the repo folder (Note: the `../game/tf` folder will already be there as it's made from the compilation). If you have
no, the single quotes cause the glob not to be expanded.

2020-09-22 17:33 UTC, int-72h commented on README.md
> +0) Make sure the path leading up the `team-comtress-2` has no spaces in it. This will lead to errors compiling protobud and gperf.
oof.

2020-09-22 17:33 UTC, int-72h commented on README.md
> +3) Install your TF2 assets into `../game/tf`. If you have TF2 and steam installed on the same drive, running `cp -rn '~/.steam/steam/steamapps/common/Team Fortress 2/*' ./` will work.
the command does the same thing. I'll change it though.

2020-09-22 17:34 UTC, int-72h commented on README.md
> +3) Install your TF2 assets into `../game/tf`. If you have TF2 and steam installed on the same drive, running `cp -rn '~/.steam/steam/steamapps/common/Team Fortress 2/*' ./` will work.
wait- saw your other comment sorry

2020-09-22 17:34 UTC, int-72h commented on README.md
> +3) Install your TF2 assets into `../game/tf`, the `game` folder should be outside the repo folder (Note: the `../game/tf` folder will already be there as it's made from the compilation). If you have
Really? this was pasted from the discord straight and it worked for me. I'll change it anyway.

2020-09-23 10:55 UTC, int-72h commented
ok weird, it's deleted the shaderdx8 file

2020-09-23 11:00 UTC, int-72h commented
fixed

2020-09-24 02:30 UTC, closed without merging

2020-09-24 12:56 UTC, int-72h commented
@melvyn2 why is this closed?

2020-09-24 12:56 UTC, int-72h commented
Oh wait- I'll remake this pr on master

2020-09-24 15:38 UTC, melvyn2 commented
@int-72h whoops, what?
Didn't mean to close this

2020-09-24 15:38 UTC, melvyn2 commented
Oh that was because I deleted the branch.

2020-09-24 15:51 UTC, int-72h commented
I'll remake it on the master branch